name: EmployeeManagementAPI
properties:
  MySqlUsername: root
  MySqlPassword: root
  MySqlHostname: "127.0.0.1"
  MySqlPort: 3306
  MySqlDbName: test
  RedisServerURL: "localhost:6379"
  StartRecordFrom: 2